IAC_PATH=./iac/

TARGET_INIT=init
TARGET_CLUSTER=cluster
TARGET_CLEAN=clean
TARGET_ALL=all
DEFAULT_TARGET=$(TARGET_ALL)

TERRAFORM_ENV_VARS+=AWS_PROFILE=$(AWS_PROFILE)
TERRAFORM_ENV_VARS+=AWS_SDK_LOAD_CONFIG=1

.PHONY: $(TARGET_INIT) $(TARGET_CLUSTER) $(TARGET_CLEAN) $(TARGET_OUTPUT) $(TARGET_ALL)

.DEFAULT_GOAL := $(DEFAULT_TARGET)

$(TARGET_INIT):
	cd $(IAC_PATH) && $(TERRAFORM_ENV_VARS) terraform init
$(TARGET_CLUSTER):
	cd $(IAC_PATH) && $(TERRAFORM_ENV_VARS) terraform apply
$(TARGET_CLEAN):
	cd $(IAC_PATH) && $(TERRAFORM_ENV_VARS) terraform destroy
$(TARGET_OUTPUT):
	cd $(IAC_PATH) && $(TERRAFORM_ENV_VARS) terraform output
$(TARGET_ALL): $(TARGET_INIT) $(TARGET_CLUSTER)

